#version: '3.8'

services:
  frontend:
    image: frontend_app
    container_name: frontend
    depends_on:
      - backend
    build:
      context: ../frontend  # Путь к Dockerfile фронтенда
      dockerfile: Dockerfile  # Имя Dockerfile для фронтенда
    ports:
      - "3000:3000"  # Пробрасываем порт для фронтенда
    networks:
      app-network:
        ipv4_address: 172.18.0.3  # Определяем сеть для связи с бэкендом
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000  # URL бэкенда для фронтэнда

  backend:
    image: backend_app
    container_name: backend
    build:
      context: ../backend  # Путь к Dockerfile бэкэнда
      dockerfile: Dockerfile  # Имя Dockerfile для бэкэнда
    ports:
      - "5000:5000"  # Пробрасываем порт для бэкенда
    volumes:
      - ../backend/data.txt:/app/data.txt  # Монтируем файл data.txt на хосте в контейнер бэка
    networks:
      app-network:
        ipv4_address: 172.18.0.2  # Подключаемся к той же сети для связи с фронтэндом

networks:
  app-network:
    driver: bridge
    ipam:
     config:
      - subnet: "172.18.0.0/16"